### ISSUE TITLE
Doesn't handle dashes in tag names

### ISSUE THREAD

**Issue by yannbertrand** [dbushell/xml-streamify#5]
xml-streamify doesn't handle XML tag names containing dashes `-`. They are escaped so `my-tag` becomes `my`.

Probably something to do with this regex https://github.com/dbushell/xml-streamify/blob/b8b3febbe66aee027f8c9fbf0179173975f0fe08/src/parse.ts#L76?

**Comment by dbushell** [comment]
Thanks I will fix this soon.
